In [1]:
import sys
from pathlib import Path
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

root = str(Path.cwd().parent)

if root not in sys.path:
    sys.path.append(root)


from src.step2_transformation import DataTransformer

In [2]:

transformer = DataTransformer(config_name='step1_features_config.yaml', max_budget=105000)


df_normalized = transformer.execute_pipeline()

display(df_normalized.head(15))

✅ YAML Config loaded successfully.

🚀 Starting ETL pipeline for file: data/car_database.csv
/media/anderson/3E9AB8FA9AB8AFAF/Users/lessi/OneDrive/Documentos/Projetos/02_Carreira/01_Portifolio/02_Car_Selection_MCDA/src/car-selection-mcda/data/car_database.csv
Filter 1: Applying Hard Constraints dynamically...
  -> Applied constraint: cost <= 105000
 -> Cars removed: 17 | Remaining: 14
Filter 2: Removing uninformative columns...
  -> Auto-dropped (Zero Variance): ['stability_control', 'leather_steering_wheel', 'leather_seats', 'transmission', 'driver_seat_height_adjustment', 'hill_start_assist', 'abs', 'traction_control', 'power_door_locks', 'handling', 'power_steering']
Transformation 1: Applying Conditional Logic dynamically...
  -> Applied FILL_NULL (1.0) for: fog_lights
  -> Applied OR_GATE substitution for: rear_view_camera
  -> Applied OR_GATE substitution for: rear_parking_sensors
Transformation 2: Applying Utility Mapping...
Transformation 3: Binarizing booleans...
Transformation 4: Continuous Normalization (Min-Max)...
✅ Pipeline Finished! Mathematical matrix generated successfully.

                     car                                         version      cost  warranty  engine  horsepower    torque  cruise_control  city_fuel_economy  highway_fuel_economy  ground_clearance  payload_capacity  airbag  air_conditioning  infotainment_system  keyless  steering_wheel_adjustment  power_windows  power_side_mirrors  rear_view_camera  rear_parking_sensors  tire_pressure_sensor  twilight_sensor  fog_lights  led_headlights  roof_rails  alloy_wheels  tow_hitch  aesthetics  freshness
0         Fiat Argo 2026                   1.0 FIREFLY FLEX DRIVE MANUAL  0.836364       0.0     0.0    0.033333  0.263158             0.0           1.000000              0.357143               0.8          0.000000     0.5               0.8                  1.0      0.0                        0.5            0.7                 0.0               0.0                   0.0                   1.0              0.0         0.0             0.0         0.0           0.0        1.0    0.000000       0.25
1         Fiat Argo 2026  1.0 FIREFLY FLEX DRIVE MANUAL + PACK DRIVE TOP  0.696970       0.0     0.0    0.033333  0.263158             0.0           1.000000              0.357143               0.8          0.000000     0.5               1.0                  1.0      1.0                        0.5            1.0                 1.0               1.0                   1.0                   1.0              0.0         1.0             0.0         0.0           0.0        1.0    0.000000       0.25
2         Fiat Argo 2026                1.3 FIREFLY FLEX TREKKING MANUAL  0.000000       0.0     1.0    1.000000  1.000000             0.0           0.000000              0.000000               1.0          0.000000     0.5               0.8                  1.0      0.0                        0.5            1.0                 1.0               1.0                   1.0                   1.0              0.0         1.0             1.0         1.0           1.0        1.0    0.666667       0.50
8      Hyundai Hb20 2026                     1.0 12V FLEX COMFORT MANUAL  0.460606       1.0     0.0    0.133333  0.000000             1.0           0.800000              0.678571               0.8          0.000000     1.0               0.8                  1.0      0.0                        0.0            0.7                 1.0               0.0                   0.0                   0.0              1.0         1.0             0.0         0.0           0.0        1.0    0.333333       0.00
9      Hyundai Hb20 2026                     1.0 12V FLEX LIMITED MANUAL  0.212121       1.0     0.0    0.133333  0.000000             1.0           0.800000              0.678571               0.8          0.000000     1.0               0.8                  1.0      1.0                        1.0            1.0                 1.0               1.0                   1.0                   0.0              1.0         1.0             0.0         0.0           1.0        1.0    0.333333       0.00
11   Chevrolet Onix 2026                                 1.0 FLEX MANUAL  0.060606       0.0     0.0    0.300000  0.052632             0.0           0.933333              1.000000               0.5          0.200000     1.0               0.8                  1.0      0.0                        0.5            1.0                 1.0               0.0                   0.0                   0.0              0.0         0.0             0.0         0.0           0.0        0.0    0.666667       1.00
12   Chevrolet Onix 2026                        1.0 FLEX MANUAL + Sensor  0.015879       0.0     0.0    0.300000  0.052632             0.0           0.933333              1.000000               0.5          0.200000     1.0               0.8                  1.0      0.0                        0.5            1.0                 1.0               1.0                   1.0                   0.0              0.0         0.0             0.0         0.0           0.0        0.0    0.666667       1.00
19  Volkswagen Polo 2026                            1.0 MPI TRACK MANUAL  0.442424       0.0     0.0    0.200000  0.052632             0.0           0.933333              0.785714               0.8          0.000000     0.8               0.8                  0.0      0.0                        1.0            0.7                 1.0               0.0                   0.0                   1.0              0.0         1.0             0.0         0.0           0.0        1.0    0.333333       0.50
20  Volkswagen Polo 2026                  1.0 MPI TRACK MANUAL + VW Play  0.339394       0.0     0.0    0.200000  0.052632             0.0           0.933333              0.785714               0.8          0.000000     0.8               0.8                  1.0      0.0                        1.0            0.7                 1.0               0.0                   0.0                   1.0              0.0         1.0             0.0         0.0           0.0        1.0    0.333333       0.50
23      Peugeot 208 2026                   1.0 FIREFLY FLEX STYLE MANUAL  0.412121       0.0     0.0    0.000000  0.105263             1.0           1.000000              0.642857               0.8          0.266667     0.8               1.0                  1.0      0.0                        1.0            1.0                 1.0               1.0                   1.0                   0.0              0.0         1.0             1.0         0.0           1.0        1.0    1.000000       1.00
26       Citroën C3 2026               1.0 FIREFLY FLEX LIVE PACK MANUAL  1.000000       0.0     0.0    0.000000  0.157895             0.0           0.733333              0.357143               1.0          1.000000     0.5               0.8                  1.0      0.0                        0.0            0.7                 0.0               0.0                   0.0                   1.0              0.0         0.0             0.0         0.0           0.0        0.0    0.333333       0.75
27       Citroën C3 2026      1.0 FIREFLY FLEX LIVE PACK MANUAL + Sensor  0.968303       0.0     0.0    0.000000  0.157895             0.0           0.733333              0.357143               1.0          1.000000     0.5               0.8                  1.0      0.0                        0.0            0.7                 0.0               1.0                   1.0                   1.0              0.0         0.0             0.0         0.0           0.0        0.0    0.333333       0.75
28       Citroën C3 2026                    1.0 FIREFLY FLEX FEEL MANUAL  0.878788       0.0     0.0    0.000000  0.157895             0.0           0.733333              0.357143               1.0          1.000000     0.5               0.8                  1.0      0.0                        0.5            1.0                 1.0               1.0                   1.0                   1.0              0.0         0.0             0.0         1.0           1.0        0.0    0.333333       0.75
29       Citroën C3 2026                     1.0 FIREFLY FLEX XTR MANUAL  0.696970       0.0     0.0    0.000000  0.157895             0.0           0.600000              0.250000               1.0          1.000000     0.5               1.0                  1.0      0.0                        0.5            1.0                 1.0               1.0                   1.0                   1.0              0.0         1.0             0.0         1.0           1.0        0.0    0.333333       0.75

In [3]:
df_normalized.describe(include='all')

                    car                        version       cost   warranty     engine  horsepower     torque  cruise_control  city_fuel_economy  highway_fuel_economy  ground_clearance  payload_capacity     airbag  air_conditioning  infotainment_system    keyless  steering_wheel_adjustment  power_windows  power_side_mirrors  rear_view_camera  rear_parking_sensors  tire_pressure_sensor  twilight_sensor  fog_lights  led_headlights  roof_rails  alloy_wheels  tow_hitch  aesthetics  freshness
count                14                             14  14.000000  14.000000  14.000000   14.000000  14.000000       14.000000          14.000000             14.000000         14.000000         14.000000  14.000000         14.000000            14.000000  14.000000                  14.000000      14.000000           14.000000         14.000000             14.000000             14.000000        14.000000   14.000000       14.000000   14.000000     14.000000  14.000000   14.000000  14.000000
unique                6                             14        NaN        NaN        NaN         NaN        NaN             NaN                NaN                   NaN               NaN               NaN        NaN               NaN                  NaN        NaN                        NaN            NaN                 NaN               NaN                   NaN                   NaN              NaN         NaN             NaN         NaN           NaN        NaN         NaN        NaN
top     Citroën C3 2026  1.0 FIREFLY FLEX DRIVE MANUAL        NaN        NaN        NaN         NaN        NaN             NaN                NaN                   NaN               NaN               NaN        NaN               NaN                  NaN        NaN                        NaN            NaN                 NaN               NaN                   NaN                   NaN              NaN         NaN             NaN         NaN           NaN        NaN         NaN        NaN
freq                  4                              1        NaN        NaN        NaN         NaN        NaN             NaN                NaN                   NaN               NaN               NaN        NaN               NaN                  NaN        NaN                        NaN            NaN                 NaN               NaN                   NaN                   NaN              NaN         NaN             NaN         NaN           NaN        NaN         NaN        NaN
mean                NaN                            NaN   0.501468   0.142857   0.071429    0.166667   0.176692        0.214286           0.795238              0.543367          0.828571          0.333333   0.707143          0.842857             0.928571   0.142857                   0.535714       0.871429            0.785714          0.571429              0.571429              0.642857         0.142857    0.571429        0.142857    0.214286      0.357143   0.571429    0.404762   0.571429
std                 NaN                            NaN   0.351063   0.363137   0.267261    0.264414   0.251657        0.425815           0.260787              0.295565          0.168379          0.446831   0.226900          0.085163             0.267261   0.363137                   0.365023       0.154066            0.425815          0.513553              0.513553              0.497245         0.363137    0.513553        0.363137    0.425815      0.497245   0.513553    0.267261   0.345696
min                 NaN                            NaN   0.000000   0.000000   0.000000    0.000000   0.000000        0.000000           0.000000              0.000000          0.500000          0.000000   0.500000          0.800000             0.000000   0.000000                   0.000000       0.700000            0.000000          0.000000              0.000000              0.000000         0.000000    0.000000        0.000000    0.000000      0.000000   0.000000    0.000000   0.000000
25%                 NaN                            NaN   0.243939   0.000000   0.000000    0.000000   0.052632        0.000000           0.733333              0.357143          0.800000          0.000000   0.500000          0.800000             1.000000   0.000000                   0.500000       0.700000            1.000000          0.000000              0.000000              0.000000         0.000000    0.000000        0.000000    0.000000      0.000000   0.000000    0.333333   0.312500
50%                 NaN                            NaN   0.451515   0.000000   0.000000    0.083333   0.131579        0.000000           0.866667              0.500000          0.800000          0.100000   0.650000          0.800000             1.000000   0.000000                   0.500000       1.000000            1.000000          1.000000              1.000000              1.000000         0.000000    1.000000        0.000000    0.000000      0.000000   1.000000    0.333333   0.625000
75%                 NaN                            NaN   0.801515   0.000000   0.000000    0.200000   0.157895        0.000000           0.933333              0.758929          1.000000          0.816667   0.950000          0.800000             1.000000   0.000000                   0.875000       1.000000            1.000000          1.000000              1.000000              1.000000         0.000000    1.000000        0.000000    0.000000      1.000000   1.000000    0.583333   0.750000
max                 NaN                            NaN   1.000000   1.000000   1.000000    1.000000   1.000000        1.000000           1.000000              1.000000          1.000000          1.000000   1.000000          1.000000             1.000000   1.000000                   1.000000       1.000000            1.000000          1.000000              1.000000              1.000000         1.000000    1.000000        1.000000    1.000000      1.000000   1.000000    1.000000   1.000000